### ISSUE TITLE
Wanted to improve contact page

### ISSUE THREAD

**Issue by abhijain2003** [abhinavkashyap061/Dear-Diary#8]
Hey I wanted to improve contact page by adding icons instead of direct links

please assign me under hacktoberfest 2022

and please under hacktoberfest my last 2 pr got excluded from hacktoberfest 2022 don't know why
i am new to open source so any guidance would be appreciate
and really needed

**Comment by abhinavkashyap061** [comment]
Hey @abhijain2003  👋, Thanks for considering contributing to my project

- ok i am assigning you this task of improving icons. 
- yes, this project is under hacktoberfest as per the guidelines. i think that might happen because your contributions might deviated from hacktoberfest guidelines. I am trying to encourage quality contributions as much as i can through these projects for hacktoberfest 2022. if yours still get excluded, ping me afterwards, i will help you mate!

Happy Hacking 🚀

**Comment by abhijain2003** [comment]
sure as I heard open source community are so helpful

**Comment by abhijain2003** [comment]
Hey this is ejs folder and it is connected with mongodb database localhost i am getting error on connecting with database can you help me out
![Screenshot 2022-10-10 224013](https://user-images.githubusercontent.com/91718608/194919128-f0ce2de9-6abc-45fb-9611-1e4c115b7055.png)

**Comment by Kritika30032002** [comment]
> Hey this is ejs folder and it is connected with mongodb database localhost i am getting error on connecting with database can you help me out ![Screenshot 2022-10-10 224013](https://user-images.githubusercontent.com/91718608/194919128-f0ce2de9-6abc-45fb-9611-1e4c115b7055.png)

also keep running "mongod" in  other git bash shell

**Comment by Kritika30032002** [comment]
May I contribute to this?

**Comment by abhijain2003** [comment]
not at all I have resolved this issue and even the pr is also commited

**Comment by Kritika30032002** [comment]
> not at all I have resolved this issue and even the pr is also commited

okay great! Congo !!

I thought you haven't completed it as you have asked the doubt above which was not answered. That's why i asked !
